// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVblXTUcXDsytOSM_WMiEevPjlMd7_0U',
    appId: '1:718440054840:web:4785fc2e3fcc932e7da6cd',
    messagingSenderId: '718440054840',
    projectId: 'car-eco-5598d',
    authDomain: 'car-eco-5598d.firebaseapp.com',
    storageBucket: 'car-eco-5598d.firebasestorage.app',
    measurementId: 'G-W8HXH2SFYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiW9r8Ua2JkA48-VjUgP6KcEDZSGdjgAM',
    appId: '1:718440054840:android:cac76f65754285f37da6cd',
    messagingSenderId: '718440054840',
    projectId: 'car-eco-5598d',
    storageBucket: 'car-eco-5598d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2IoPTziRDhYPryTno7mNAKcClhmROVfk',
    appId: '1:718440054840:ios:d1e4d89a8a7991947da6cd',
    messagingSenderId: '718440054840',
    projectId: 'car-eco-5598d',
    storageBucket: 'car-eco-5598d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2IoPTziRDhYPryTno7mNAKcClhmROVfk',
    appId: '1:718440054840:ios:d1e4d89a8a7991947da6cd',
    messagingSenderId: '718440054840',
    projectId: 'car-eco-5598d',
    storageBucket: 'car-eco-5598d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMVblXTUcXDsytOSM_WMiEevPjlMd7_0U',
    appId: '1:718440054840:web:6bc6feebe2ac51c87da6cd',
    messagingSenderId: '718440054840',
    projectId: 'car-eco-5598d',
    authDomain: 'car-eco-5598d.firebaseapp.com',
    storageBucket: 'car-eco-5598d.firebasestorage.app',
    measurementId: 'G-CS2SKRPWW3',
  );
}
